//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int Role { get; set; }
        public string Address { get; set; }
    }
}
